{
 "title": "The Northwest Project",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cohort",
    "label": "Cohort",
    "query": "select meeting_night from cohorts"
   }
  ]
 },
 "panels": [
  { "title": "Self Sufficiency Scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Intake: Housing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_family_best_description_current_situation_housing) as \"Housing\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Housing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_family_best_description_current_situation_housing) as \"Housing\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  individuals.id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Transportation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_family_best_description_current_situation_transportation) as \"Transportation\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Transportation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_family_best_description_current_situation_transportation) as \"Transportation\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  individuals.id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Education",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_primary_adult_enrolled_best_description_academic) as \"Education\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent:  Education",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_primary_adult_enrolled_best_description_academic) as \"Education\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  individuals.id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Income ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_family_best_description_current_situation_income) as \"Income\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Income ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_family_best_description_current_situation_income) as \"Income\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  individuals.id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Health Insurance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_health_insurance) as \"H Ins.\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Health Insurance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_health_insurance) as \"H Ins.\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  individuals.id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Physical Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_medical_physical_family_member_impact) as \"Phys H\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Physical Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_medical_physical_family_member_impact) as \"Phys H\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  individuals.id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Mental Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_family_best_description_current_situation_mental_health) as \"Mental H\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Mental Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_family_best_description_current_situation_mental_health) as \"Mental H\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Environment",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_primary_adult_enrolled_best_description_stressors) as \"Environment\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Environment",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_primary_adult_enrolled_best_description_stressors) as \"Environment\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Parenting",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_primary_adult_enrolled_parenting) as \"Parenting\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Parenting",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_primary_adult_enrolled_parenting) as \"Parenting\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Childcare",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_quality_childcare) as \"Childcare\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Childcare",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_quality_childcare) as \"Childcare\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Legal/Criminal",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_criminal) as \"Legal/Criminal\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Legal/Criminal",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_criminal) as \"Legal/Criminal\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Legal/Non-Criminal",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_legal_non_criminal) as \"Legal/Criminal\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Legal/Non-Criminal",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_legal_non_criminal) as \"Legal/Criminal\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Support Systems",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_support_system) \nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Support Systems",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_support_system) \nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Food",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_food) \nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Food",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_food) \nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Home Safety",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_home_safety) \nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Home Safety",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_home_safety) \nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Intake: Community Involvement",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_community_involvement) \nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Most Recent: Community Involvement",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.ssa_community_involvement) \nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\n"
    }
   ]
  },
  {
   "title": "Self Sufficiency Scores on intake",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  cohorts.meeting_night as \"Cohort\", assessments.individual_id as \"ID\", individuals.first_name as \"First Name\", \n  individuals.last_name as \"Last Name\", assessments.ssa_family_best_description_current_situation_housing as \"Housing\",\n  assessments.ssa_family_best_description_current_situation_transportation as \"Transportation\",\n  assessments.ssa_primary_adult_enrolled_best_description_academic as \"Education\",\n  assessments.ssa_family_best_description_current_situation_income as \"Income\",\n  assessments.ssa_health_insurance as \"H Ins.\",\n  assessments.ssa_medical_physical_family_member_impact as \"Phys H\",\n  assessments.ssa_family_best_description_current_situation_mental_health as \"Mental H\",\n  assessments.ssa_primary_adult_enrolled_best_description_stressors as \"Environ\",\n  assessments.ssa_primary_adult_enrolled_parenting as \"Parenting\",\n  assessments.ssa_quality_childcare as \"Childcare\",\n  assessments.ssa_criminal as \"Legal / Crim\",\n  assessments.ssa_legal_non_criminal as \"Legal / Non-Crim\",\n  assessments.ssa_support_system as \"Support System\",\n  assessments.ssa_food as \"Food\",\n  assessments.ssa_home_safety as \"Home Safety\",\n  assessments.ssa_community_involvement as \"Community Involvement\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\nORDER BY\n  cohorts.meeting_night, assessments.individual_id asc"
    }
   ]
  },
  {
   "title": "Most Recent Self Sufficiency Scores",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  cohorts.meeting_night as \"Cohort\", assessments.individual_id as \"ID\", individuals.first_name as \"First Name\", \n  individuals.last_name as \"Last Name\", assessments.ssa_family_best_description_current_situation_housing as \"Housing\",\n  assessments.ssa_family_best_description_current_situation_transportation as \"Transportation\",\n  assessments.ssa_primary_adult_enrolled_best_description_academic as \"Education\",\n  assessments.ssa_family_best_description_current_situation_income as \"Income\",\n  assessments.ssa_health_insurance as \"H Ins.\",\n  assessments.ssa_medical_physical_family_member_impact as \"Phys H\",\n  assessments.ssa_family_best_description_current_situation_mental_health as \"Mental H\",\n  assessments.ssa_primary_adult_enrolled_best_description_stressors as \"Environ\",\n  assessments.ssa_primary_adult_enrolled_parenting as \"Parenting\",\n  assessments.ssa_quality_childcare as \"Childcare\",\n  assessments.ssa_criminal as \"Legal / Crim\",\n  assessments.ssa_legal_non_criminal as \"Legal / Non-Crim\",\n  assessments.ssa_support_system as \"Support System\",\n  assessments.ssa_food as \"Food\",\n  assessments.ssa_home_safety as \"Home Safety\",\n  assessments.ssa_community_involvement as \"Community Involvement\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort)\nORDER BY\n  cohorts.meeting_night, assessments.individual_id asc"
    }
   ]
  },
  { "title": "Credit Scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Earliest Credit Score: Average",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.credit_score) as \"Credit Score\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS first_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = first_assessments.individual_id AND\n  individuals.id = first_assessments.individual_id AND\n  assessments.date_collected = first_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort) AND\n  assessments.credit_score > 0\n"
    }
   ]
  },
  {
   "title": "Most Recent Credit Score: Average",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  avg(assessments.credit_score) as \"Credit Score\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments, assessments, individuals, cohorts\nWHERE\n  assessments.individual_id = latest_assessments.individual_id AND\n  individuals.id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  individuals.cohort_id = cohorts.id AND cohorts.meeting_night IN ($Cohort) AND\n  assessments.credit_score > 0\n"
    }
   ]
  },
  {
   "title": "Earliest Credit Scores",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  assessments.individual_id as \"ID\", assessments.credit_score as \"Credit Score\"\nFROM\n  (SELECT\n     individual_id, MIN(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments\nINNER JOIN\n  assessments\nON\n  assessments.individual_id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  assessments.credit_score > 0\nORDER BY\n  assessments.credit_score desc"
    }
   ]
  },
  {
   "title": "Most Recent Credit Scores",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT\n  assessments.individual_id as \"ID\", assessments.credit_score as \"Credit Score\"\nFROM\n  (SELECT\n     individual_id, MAX(date_collected) AS date_collected\n   FROM\n     assessments\n   GROUP BY\n     individual_id) AS latest_assessments\nINNER JOIN\n  assessments\nON\n  assessments.individual_id = latest_assessments.individual_id AND\n  assessments.date_collected = latest_assessments.date_collected AND\n  assessments.credit_score > 0\nORDER BY\n  assessments.credit_score desc"
    }
   ]
  }
 ]
}