version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    ports:
          - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      # first run used postgres: volume to setup db, 2nd run uses volume below for db import.
      #- '/Users/shannonmcmurtrey/Dropbox/Development/rails_projects/nwp/data:/var/lib/postgresql/data'
    env_file:
      - '.env'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '80:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  dashboard:
    image: 'grafana/grafana'
    env_file: 
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'
    ports: 
      - '3001:3000'
    

volumes:
  redis:
  postgres:
  grafana_data:
