class AddScreeningFieldsToIndividual < ActiveRecord::Migration[5.0]
  def change
    add_column :individuals, :date_of_application, :date
    add_column :individuals, :alternate_phone, :string
    add_column :individuals, :willing_and_able_to_commit_to_program, :boolean
    add_column :individuals, :specific_days_that_do_not_work, :integer
    add_column :individuals, :days_and_times_not_available, :text
    add_column :individuals, :currently_employed, :integer
    add_column :individuals, :employed_full_or_part_time, :integer
    add_column :individuals, :employer, :string
    add_column :individuals, :position, :string
    add_column :individuals, :avg_hours_worked_per_week, :float
    add_column :individuals, :hourly_wage, :float
    add_column :individuals, :salary, :float
    add_column :individuals, :employer_benefits, :text
    add_column :individuals, :not_employed_but_eligible, :boolean
    add_column :individuals, :how_many_jobs_in_last_six_months, :integer
    add_column :individuals, :total_family_income_from_all_sources, :float
    add_column :individuals, :child_support, :integer
    add_column :individuals, :other_sources_of_income, :text
    add_column :individuals, :currently_file_taxes, :boolean
    add_column :individuals, :receive_earned_income_tax_credit, :boolean
    add_column :individuals, :highest_education_attained, :integer
    add_column :individuals, :highest_education_attained_by_parent_or_caretaker, :string
    add_column :individuals, :marital_status, :integer
    add_column :individuals, :children_living_outside_home, :boolean
    add_column :individuals, :children_outside_home_who, :string
    add_column :individuals, :parenting_class, :integer
    add_column :individuals, :parenting_class_which, :string
    add_column :individuals, :quality_childcare, :integer
    add_column :individuals, :children_currently_in_quality_care, :boolean
    add_column :individuals, :children_in_quality_care_explain, :text
    add_column :individuals, :have_health_care_in_some_form, :boolean
    add_column :individuals, :have_health_care_in_some_form_explain, :string
    add_column :individuals, :children_have_health_care_in_some_form, :boolean
    add_column :individuals, :children_have_health_care_in_some_form_explain, :string
    add_column :individuals, :currently_have_stable_housing, :boolean
    add_column :individuals, :rent_or_own, :integer
    add_column :individuals, :monthly_rent_or_mortgage_payment, :float
    add_column :individuals, :receive_rent_rebate, :boolean
    add_column :individuals, :currently_receive_public_housing_assistance, :boolean
    add_column :individuals, :currently_receive_private_subsidized_housing_assistance, :boolean
    add_column :individuals, :use_section_eight_voucher, :boolean
    add_column :individuals, :currently_have_reliable_transportation, :boolean
    add_column :individuals, :reliable_transportation_method, :integer
    add_column :individuals, :reliable_transportation_method_other, :string
    add_column :individuals, :possible_to_obtain_reliable_transportation_in_sixty_days, :boolean
    add_column :individuals, :have_required_auto_insurance, :boolean
    add_column :individuals, :have_valid_id_or_drivers_license, :boolean
    add_column :individuals, :no_valid_id_or_license_reason, :integer
    add_column :individuals, :revoked_or_suspended_license_explanation, :text
    add_column :individuals, :ever_convicted_of_felony, :boolean
    add_column :individuals, :ever_convicted_of_misdemeanor, :boolean
    add_column :individuals, :current_pending_court_cases, :boolean
    add_column :individuals, :any_legal_matters_needing_resolution, :boolean
    add_column :individuals, :nwp_assets_family, :boolean
    add_column :individuals, :nwp_assets_lives_in_neighborhood, :boolean
    add_column :individuals, :nwp_assets_accountability, :boolean
    add_column :individuals, :nwp_assets_parenting_training, :boolean
    add_column :individuals, :nwp_assets_ged_highschool_college, :boolean
    add_column :individuals, :nwp_assets_transportation, :boolean
    add_column :individuals, :nwp_assets_stable_housing, :boolean
    add_column :individuals, :nwp_assets_quality_childcare, :boolean
    add_column :individuals, :nwp_assets_earned_income_tax_credit, :boolean
    add_column :individuals, :nwp_assets_resolved_criminal_background_na, :boolean
    add_column :individuals, :nwp_assets_monthly_budget_management, :boolean
    add_column :individuals, :nwp_assets_health_care_insurance, :boolean
    add_column :individuals, :nwp_currently_eligible, :boolean
    add_column :individuals, :square_footage_of_house, :float
    add_column :individuals, :notes, :text
    add_column :individuals, :preferred_method_of_contact, :text
  end
end
